### ISSUE TITLE
warn: API KEY 노출

### ISSUE THREAD

**Issue by whitedev7773** [jinnu-dev/melobot#1]
결제 수단 연결 안해둔 DB라 괜찮은데 혹시 몰라 이슈 올립니당.
![image](https://github.com/user-attachments/assets/dce2b524-bad8-412d-9606-876e9199fbde)

마찬가지로 카카오 TTS API키도 노출은 됬어요. 지금은 지원 종료된 API라서 괜찮지만 요것도 파이어베이스 키 지울 때 같이 지워주시면 감사하겠습니당 
![image](https://github.com/user-attachments/assets/faf2327c-1484-46ab-b5a7-ee827ac13103)

어릴 때 짠 코드 보다가 좀 많이 더럽게 짰다는 생각이 드네요. 죄송합니다..!ㅋㅋㅋ

**Comment by jinnu-dev** [comment]
얘기 해줘서 땡큐 수정 전부 해뒀어~
